Updated pyton-practice.yaml & captured failed script to errors.log

diff --git a/.github/workflows/python-practice.yaml b/.github/workflows/python-practice.yaml
--- a/.github/workflows/python-practice.yaml
+++ b/.github/workflows/python-practice.yaml
@@ -24,33 +24,43 @@ jobs:
           python-version: "3.11"
 
       - name: Run Script 1
-        run: python script1.py
+        run: python script1.py || echo "script1 failed" >> errors.log
 
       - name: Run Script 2
-        run: python script2.py
+        run: python script2.py || echo "script2 failed" >> errors.log
         
       - name: Run Script 3
-        run: python script3.py
+        run: python script3.py || echo "script3 failed" >> errors.log
 
       - name: Run Script with ENV
-        run: python script4.py
+        run: python script4.py || echo "script4 failed" >> errors.log
         env:
           APP_ENV: production
 
       - name: Run Script 5
-        run: python script5.py
+        run: python script5.py || echo "script5 failed" >> errors.log
 
       - name: Run Script 6
-        run: python script6.py
+        run: python script6.py || echo "script6 failed" >> errors.log
       
       - name: Run Script 7
-        run: python script7.py
+        run: python script7.py || echo "script7 failed" >> errors.log
         env:
           API_KEY: API7890
         
       - name: Run Script 8
-        run: python script8.py
+        run: python script8.py || echo "script8 failed" >> errors.log
         env:
-          API_KEY: API7890
+          API_KEY: API7890 
+
+      - name: Final Check
+        run: |
+          if [ -f errors.log ]; then
+            echo "Some scripts failed:"
+            cat errors.log
+            exit 1
+          else
+            echo "All scripts passed"
+          fi
         
 
